### ISSUE TITLE
can not installed in macos m1 max

### ISSUE THREAD

**Issue by freedombin** [alkaline-ml/pmdarima#512]
### Describe the question you have

sorry to bother you that I found it is always failed install.
I do not know whether i had a wrong numpy or using m1 silicon chip.
Here is ERROR detile:
  × Running setup.py install for pmdarima did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Partial import of pmdarima during the build process.
      Requirements: ['joblib>=0.11', 'Cython>=0.29,!=0.29.18', 'numpy>=1.19.3', 'pandas>=0.19', 'scikit-learn>=0.22', 'scipy>=1.3.2', 'statsmodels>=0.11,!=0.12.0', 'urllib3', 'setuptools>=38.6.0,!=50.0.0']
      Adding extra setuptools args
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/pj/rbsf6t1x2mj1njyr6dhy8gm00000gn/T/pip-install-slnnhces/pmdarima_2c8d101ca8ab4a9ebdffcf0b5137682d/setup.py", line 335, in <module>
          do_setup()
        File "/private/var/folders/pj/rbsf6t1x2mj1njyr6dhy8gm00000gn/T/pip-install-slnnhces/pmdarima_2c8d101ca8ab4a9ebdffcf0b5137682d/setup.py", line 324, in do_setup
          from numpy.distutils.core import setup
        File "/Users/miniforge3/lib/python3.9/site-packages/numpy/distutils/core.py", line 24, in <module>
          from numpy.distutils.command import config, config_compiler, \
        File "/Users/miniforge3/lib/python3.9/site-packages/numpy/distutils/command/config.py", line 19, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File "/Users/miniforge3/lib/python3.9/site-packages/numpy/distutils/mingw32ccompiler.py", line 28, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]

thanks for your read

**Comment by sensei-jirving** [comment]
I am also getting this issue, as of today. I had just installed it successfully last week.
One of my students had an error when trying to install, so I uninstalled my conda environment and re-created it and now I am receiving this error, too. 

I am also using miniforge.

**Comment by aaronreidsmith** [comment]
Conda distributions are actually maintained in https://github.com/conda-forge/pmdarima-feedstock by a separate group of maintainers, but as of 2.0.1 (released today) we support M1 chips via `pip`. So you might try `pip install pmdarima==2.0.1` and see if that helps!
