### ISSUE TITLE
Failed to install pmdarima in Python 3.13

### ISSUE THREAD

**Issue by yash-2910** [alkaline-ml/pmdarima#588]
### Describe the bug

I'm not able to install the package using Python v3.13
Building wheels for collected packages: pmdarima
  Building wheel for pmdarima (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pmdarima (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      Partial import of pmdarima during the build process.
      Requirements: ['joblib>=0.11', 'Cython>=0.29,!=0.29.18,!=0.29.31', 'numpy>=1.21.2', 'pandas>=0.19', 'scikit-learn>=0.22', 'scipy>=1.3.2', 'statsmodels>=0.13.2', 'urllib3', 'setuptools>=38.6.0,!=50.0.0', 'packaging>=17.1  # Bundled with setuptools, but want to be explicit']
      Adding extra setuptools args
      Setting up with setuptools
      Traceback (most recent call last):
        File "/home/yash/Documents/venvs/seasonality313/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/home/yash/Documents/venvs/seasonality313/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/yash/Documents/venvs/seasonality313/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                              metadata_directory)
                                              ^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-tc6d03gr/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 437, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
        File "/tmp/pip-build-env-tc6d03gr/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 425, in _build
          return self._build_with_temp_dir(
                 ~~~~~~~~~~~~~~~~~~~~~~~~~^
              cmd,
              ^^^^
          ...<3 lines>...
              self._arbitrary_args(config_settings),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "/tmp/pip-build-env-tc6d03gr/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 406, in _build_with_temp_dir
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-tc6d03gr/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 521, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-tc6d03gr/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 319, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 371, in <module>
        File "<string>", line 330, in do_setup
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pmdarima
Failed to build pmdarima
ERROR: Could not build wheels for pmdarima, which is required to install pyproject.toml-based projects


### To Reproduce

1. Set Python v3.13
2. run pip install pmdarima

### Versions

```shell
Linux-5.15.0-107-generic-x86_64-with-glibc2.31
Python 3.13.0 (main, Oct  8 2024, 08:51:27) [GCC 9.4.0]
not able to install pmdarima
```


### Expected Behavior

Get package installed

### Actual Behavior

Failling installation process.

### Additional Context

_No response_

**Comment by aaronreidsmith** [comment]
Thanks for the report. This is currently blocked by #577 (Numpy 2+ support), since Numpy does not have wheels for Python 3.13 on the 1.X branch. We're working on that, and then we can address this

**Comment by cavourmartinelli** [comment]
Hello @aaronreidsmith, I am also having an issue related to pmdarima installation (see below). Is seems to be the same as the one reported above by @yash-2910. Is there any workaround or we still have to wait?

`error: subprocess-exited-with-error
  
  Building wheel for pmdarima (pyproject.toml) did not run successfully.
  exit code: 1
  
  [41 lines of output]
  Partial import of pmdarima during the build process.
  
  Requirements: ['joblib>=0.11\nCython>=0.29,!=0.29.18,!=0.29.31\nnumpy>=1.21.2\npandas>=0.19\nscikit-learn>=0.22\nscipy>=1.3.2\nstatsmodels>=0.13.2\nurllib3\nsetuptools>=38.6.0,!=50.0.0\npackaging>=17.1  # Bundled with setuptools, but want to be explicit\n']
  Adding extra setuptools args
  Setting up with setuptools
  Traceback (most recent call last):
    File "C:\Users\Kátia Bettoni\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
      ~~~~^^
    File "C:\Users\Kátia Bettoni\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Kátia Bettoni\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                          metadata_directory)
                                          ^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Kátia Bettoni\AppData\Local\Temp\pip-build-env-pz18f75q\overlay\Lib\site-packages\setuptools\build_meta.py", line 438, in build_wheel
      return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
    File "C:\Users\Kátia Bettoni\AppData\Local\Temp\pip-build-env-pz18f75q\overlay\Lib\site-packages\setuptools\build_meta.py", line 426, in _build
      return self._build_with_temp_dir(
             ~~~~~~~~~~~~~~~~~~~~~~~~~^
          cmd,
          ^^^^
      ...<3 lines>...
          self._arbitrary_args(config_settings),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      )
      ^
    File "C:\Users\Kátia Bettoni\AppData\Local\Temp\pip-build-env-pz18f75q\overlay\Lib\site-packages\setuptools\build_meta.py", line 407, in _build_with_temp_dir
      self.run_setup()
      ~~~~~~~~~~~~~~^^
    File "C:\Users\Kátia Bettoni\AppData\Local\Temp\pip-build-env-pz18f75q\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
      super().run_setup(setup_script=setup_script)
      ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Kátia Bettoni\AppData\Local\Temp\pip-build-env-pz18f75q\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
      exec(code, locals())
      ~~~~^^^^^^^^^^^^^^^^
    File "<string>", line 371, in <module>
    File "<string>", line 330, in do_setup
  ModuleNotFoundError: No module named 'numpy'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pmdarima
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pmdarima)`

**Comment by amotl** [comment]
Hi there,

we are currently aiming to modernize PyCaret, and are also blocked on this.

- https://github.com/pycaret/pycaret/issues/4121

With kind regards,
Andreas.

**Comment by swiftclouddbs** [comment]
We also are getting the numpy error also with Python 3.13.  We are patient.  Thanks!!

**Comment by pawxnsingh** [comment]
@Emzzyliano yes this exist

**Comment by Monofascia** [comment]
> Up till today, this error still exists. I've also tried installing it on Python v3.11 still not working. Please is there a way around this issue now?
With Python 3.12.7 works

**Comment by hyunbinseo** [comment]
I can confirm that installation works on 3.12.x

```shell
# ModuleNotFoundError: No module named 'numpy'
uv init --python 3.13 && uv add numpy pmdarima
# Using CPython 3.13.2

# works
uv init --python 3.12 && uv add numpy pmdarima
# Using CPython 3.12.9

# advised
uv init --python 3.12 && uv add "numpy<2" pmdarima
# Using CPython 3.12.9

# [[package]]
# name = "numpy"
# version = "1.26.4"
```
